apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-pod
      app: homework
  template:
    metadata:
      name: fronend-pod
      labels:
        name: frontend-pod
        app: homework
    spec:
      containers:
        - name: frontend
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
